#!/bin/bash

set -euo pipefail

. deploy_lib.sh

usage() {
    cat <<-EOF
    usage: $(basename $0) init <pub key path> <remote path>
           $(basename $0) deploy
EOF
    exit 1
}

test "$#" == 0 && usage

case "$1" in
    init)
        shift
        # <key> <deploy dir>
        init_deploy "$1" "$2"
        ;;
    deploy)
        shift;;
    *)
        usage
    ;;
esac
