#!/bin/bash

set -euo pipefail

. deploy_lib.sh

usage() {
    cat <<-EOF
		usage: $(basename $0) init <pub key path> <remote path> [ssh options]
		       $(basename $0) remote [command]
		       $(basename $0) deploy <remote>
EOF
    exit 1
}

test "$#" == 0 && usage

case "$1" in
    init)
        shift
        # <key> <deploy dir> <remaining optional ssh options>
        init_deploy "$@"
        ;;
    deploy)
        shift;;
    *)
        usage
    ;;
esac
